# Generated by Django 5.1.1 on 2024-09-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_user_is_email_verified_user_otp_user_otp_expire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='taskmanager',
            name='task_description',
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='taskmanager',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
